// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: protos/piefiredire.proto

package piefiredire

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PieFireDireServiceClient is the client API for PieFireDireService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PieFireDireServiceClient interface {
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error)
}

type pieFireDireServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPieFireDireServiceClient(cc grpc.ClientConnInterface) PieFireDireServiceClient {
	return &pieFireDireServiceClient{cc}
}

func (c *pieFireDireServiceClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*GetSummaryResponse, error) {
	out := new(GetSummaryResponse)
	err := c.cc.Invoke(ctx, "/proto.PieFireDireService/GetSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PieFireDireServiceServer is the server API for PieFireDireService service.
// All implementations must embed UnimplementedPieFireDireServiceServer
// for forward compatibility
type PieFireDireServiceServer interface {
	GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error)
	mustEmbedUnimplementedPieFireDireServiceServer()
}

// UnimplementedPieFireDireServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPieFireDireServiceServer struct {
}

func (UnimplementedPieFireDireServiceServer) GetSummary(context.Context, *GetSummaryRequest) (*GetSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedPieFireDireServiceServer) mustEmbedUnimplementedPieFireDireServiceServer() {}

// UnsafePieFireDireServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PieFireDireServiceServer will
// result in compilation errors.
type UnsafePieFireDireServiceServer interface {
	mustEmbedUnimplementedPieFireDireServiceServer()
}

func RegisterPieFireDireServiceServer(s grpc.ServiceRegistrar, srv PieFireDireServiceServer) {
	s.RegisterService(&PieFireDireService_ServiceDesc, srv)
}

func _PieFireDireService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PieFireDireServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PieFireDireService/GetSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PieFireDireServiceServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PieFireDireService_ServiceDesc is the grpc.ServiceDesc for PieFireDireService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PieFireDireService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PieFireDireService",
	HandlerType: (*PieFireDireServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSummary",
			Handler:    _PieFireDireService_GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/piefiredire.proto",
}
